name: Deploy Next.js to Alibaba Cloud ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "20.10.0"

      - name: Install pnpm
        run: npm install -g pnpm@9.4.0

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            echo "Shell: $SHELL"
            echo "PATH before: $PATH"

            # 1. 加载 NVM 并切换 Node 版本
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install 20.10.0
            nvm use 20.10.0

            # 2. 确认 node/npm/pnpm/pm2 可用
            node -v
            npm -v
            which pnpm || npm install -g pnpm@9.4.0
            which pm2 || npm install -g pm2

            echo "PATH after: $PATH"
            which node
            which npm
            which pnpm
            which pm2

            # 3. 进入部署目录
            mkdir -p /home/interview-guide
            cd /home/interview-guide

            # 4. 拉取/更新代码
            if [ ! -d ".git" ]; then
              echo "Cloning the repository..."
              rm -rf /home/interview-guide/*
              git clone git@github.com:ccc1018/store-web-backend.git .
            else
              git remote set-url origin git@github.com:ccc1018/store-web-backend.git
              git fetch origin main
              git reset --hard origin/main
            fi

            # 5. 安装依赖
            pnpm install || npm install

            # 6. 构建项目
            pnpm run build || npm run build

            # 7. 启动/重启服务
            pm2 restart interview-guide || pm2 start "pnpm start" --name interview-guide || pm2 start "npm start" --name interview-guide
